CELL_SIZE = 100

EMPTY_CELL = "."

WHITE = "w"
BLACK = "b"

PIECE_KING   = "K"
PIECE_QUEEN  = "Q"
PIECE_ROOK   = "R"
PIECE_BISHOP = "B"
PIECE_KNIGHT = "N"
PIECE_PAWN   = "P"

SLIDING_PIECES = {PIECE_QUEEN, PIECE_ROOK, PIECE_BISHOP}

VALID_TOKENS = {
    EMPTY_CELL,
    "wK", "wQ", "wR", "wB", "wN", "wP",
    "bK", "bQ", "bR", "bB", "bN", "bP",
}

ERROR_ROW_WIDTH_MISMATCH = "ERROR ROW_WIDTH_MISMATCH"
ERROR_UNKNOWN_TOKEN      = "ERROR UNKNOWN_TOKEN"
